### ISSUE TITLE
Error Running Docker Container with GPU Support

### ISSUE THREAD

**Issue by smcch** [lidialuq/resect-glio#1]
Hi @lidialuq,

I attempted to launch your container, but encountered the following error:

docker: error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Mode auto-detected as 'legacy
nvidia-container-cli: Mount error: file creation failed: /var/lib/docker/overlay2/e055c6a05a3668f5a5e2f00e037c48a8e358b961603e88e04d4df388c8f35bca/merged/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown.

Operating System: Ubuntu 20.04 WSL
CUDA: 12.4.1

I've successfully run other GPU-based containers, so I'm puzzled by this issue. Could you please offer some guidance on how to resolve it?

Regards, 

Santiago

**Comment by lidialuq** [comment]
Hi Santiago, 
The container has been tested on the same CUDA version, but another OS. I'll need some more information since I can't reproduce the error on the setups I have access to: 

1. Is this the output of running `docker run -it --gpus all lidluq/seg-pipeline nvidia-smi`?
2. Do you get the same error when running `docker run -it --gpus all --device /dev/nvidia1 --device /dev/nvidia-uvm --device /dev/nvidia-uvm-tools --device /dev/nvidiactl lidluq/seg-pipeline nvidia-smi`?
3. Can you download the newest docker image version `docker pull lidluq/seg-pipeline:2.0` and check again whether the container has access to the GPU? (with the commands above). 

Cheers,
Lidia

**Comment by smcch** [comment]
Thanks Lidia, 

1. Yes, this is the output from docker run -it --gpus all lidluq/seg-pipeline nvidia-smi
2. After running docker run -it --gpus all --device /dev/nvidia1 --device /dev/nvidia-uvm --device /dev/nvidia-uvm-tools --device /dev/nvidiactl lidluq/seg-pipeline nvidia-smi  I get  docker: Error response from daemon: error gathering device information while adding custom device "/dev/nvidia1": no such file or directory.
3. I already downloaded the newest docker version

**Comment by lidialuq** [comment]
Thanks Santiago for debugging. It seems that removing two files (similar to [this fix](https://forums.developer.nvidia.com/t/wsl-modulus-docker-run-error-libnvidia-ml-so-1-file-exists-unknown/256058/7)) resolves the issue. I've made a new docker image without these files that can be downloaded with `docker pull lidluq/seg-pipeline:libcudafix`.

For future reference, the files are `/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1` and ` /usr/lib/x86_64-linux-gnu/libcuda.so.1`.
